services:
  - type: web
    name: gate-portal-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: "5001"
      - key: MONGO_URI
        value: "your_mongo_uri"
      - key: JWT_SECRET
        value: "your_jwt_secret"
